cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :color, inclusion: { in: %w(red green blue yellow white black grey),
    message: "not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "not a valid sex" }

  has_many :cat_rental_requests, dependent: :destroy,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest

  def age
    ((Time.zone.now - self.birthdate.to_time) / 1.year.seconds).floor
  end



end

cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validate :overlapping_requests

  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: { in: %w(PENDING APPROVED DENIED),
    message: "not a valid status" }

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat


  def overlapping_requests
    CatRentalRequest.where(':cat_id = ?', self.id)
  end


end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cats_url
    else
      redirect_to cats_url
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cats_url
    end
  end

  def destroy
     cat = Cat.find(params[:id])
    if cat.destroy
      redirect_to cats_url
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birthdate, :color, :sex, :description)
  end
end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/views/cats/_form.html.erb
  <% if :type == :edit %>
  <form action="<%= cat_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <% else %>
  <form action="<%= cats_url %>" method="post">

  <% end %>
  <label for="cat[name]">name</label>
  <input name="cat[name]" value="<%= @cat.name %>" type="text">
  <br>
  <br>
  <div>
    <% opposite = (@cat.sex == "M" ? "F" : "M" ) %>
    <input checked type="radio" id="<%= @cat.sex %>" name="cat[sex]" value="<%= @cat.sex %>" />
    <label for="<%= @cat.sex %>"><%= @cat.sex %></label>
    <input type="radio" id="<%= opposite %>" name="cat[sex]" value="<%= opposite %>" />
    <label for="<%= opposite %>"><%= opposite %></label>

  </div>
  <select name="cat[color]">
    <option selected value="<%= @cat.color %>"><%= @cat.color %></option>
    <option value="red">red</option>
    <option value="green">green</option>
    <option value="blue">blue</option>
    <option value="yellow">yellow</option>
    <option value="white">white</option>
    <option value="black">black</option>
    <option value="grey">grey</option>
  </select>

  <br>
  <label for="cat[birthdate]">birthdate</label>
  <input type='date' name="cat[birthdate]" value="<%= @cat.birthdate %>">
  <br>

  <label for="cat[description]">description</label>
  <textarea name="cat[description]"><%= @cat.description %></textarea>

  <br>
  <% if :type == :edit %>
  <input type="submit" value="Edit Cat">
  <% else %>
  <input type="submit" value="Create Cat">

  <% end %>


</form>

cats/app/views/cats/_show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="4"><%= cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Sex:</td>
            <td><%= cat.sex %></td>
        </tr>
        <tr>
            <td>Color:</td>
            <td><%= cat.color %></td>
        </tr>
        <tr>
            <td>Age:</td>
            <td><%= cat.age %></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><%= cat.description %></td>
        </tr>
    </tbody>
</table>

cats/app/views/cats/edit.html.erb
<h1>edit cat</h1>

<%= render 'form', cat: @cat, type: :edit %>

cats/app/views/cats/index.html.erb
<h1>All cats!</h1>
<a href="<%= new_cat_url %>">Create New Cat</a>
<ul>
  <% @cats.each do |cat| %>
  <li>
    <%= cat.name %>
    <br>
    <a href="<%= cat_url(cat) %>">Show Cat</a>
  </li>
  <br>
  <% end %>
</ul>

cats/app/views/cats/new.html.erb
<h1>Create new cat</h1>
<% @cat = Cat.new %>
<%= render 'form', cat: @cat, type: :new %>

cats/app/views/cats/show.html.erb
<%= render "show", cat: @cat %>
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type='submit' value="Delete Cat!">
</form>

<form action="<%= edit_cat_url %>" method="post">
  <input type="hidden" name="_method" value="get">
  <input type='submit' value="Edit Cat!">
</form>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>